Change pk to row number 4 5
windust/community-manager pull request #13
Opened 2019-04-15 19:47 UTC by Troemer16

Primary key is now row number

2019-04-20 20:44 UTC, windust requested changes

2019-04-20 20:44 UTC, windust commented on src/main/java/com/spinningnoodle/communitymanager/datastorage/GoogleSheets.java
> +            row.put("primaryKey",rowNum + "");
why the + ""?, you can just remove it...If you need to cast it, make it (String) rowNum, or better String.valueOf (rowNum)

2019-04-20 20:44 UTC, windust commented on src/main/java/com/spinningnoodle/communitymanager/datastorage/GoogleSheets.java
>              if (attributeName.getClass().toString().equals("class java.lang.String")) {
do assignableFrom, or InstanceOf instaed of checking the "Class" https://www.baeldung.com/java-instanceof

2019-04-20 20:44 UTC, windust commented on src/main/java/com/spinningnoodle/communitymanager/datastorage/GoogleSheets.java
> +//        for(int rowIndex = 0; rowIndex < values.size(); rowIndex++){
you can remove the comments if not being used... unless is for new stuff

2019-04-22 00:34 UTC, feltonm commented on src/main/java/com/spinningnoodle/communitymanager/datastorage/GoogleSheets.java
> +            row.put("primaryKey",rowNum + "");
Made change on the implement OAuth branch so we'll have it.

2019-04-22 00:54 UTC, feltonm commented on src/main/java/com/spinningnoodle/communitymanager/datastorage/GoogleSheets.java
>              if (attributeName.getClass().toString().equals("class java.lang.String")) {
made change on the implement OAuth branch so we'll have it.

2019-04-22 00:59 UTC, feltonm commented on src/main/java/com/spinningnoodle/communitymanager/datastorage/GoogleSheets.java
> +//        for(int rowIndex = 0; rowIndex < values.size(); rowIndex++){
Removed on the implement OAuth branch. It does risk the row number changing now.

2019-04-22 02:55 UTC, merged