Implement oauth
windust/community-manager pull request #14
Opened 2019-04-18 22:33 UTC by QuentinGuenther

This PR includes everything from the last PR and adds filtering meetups.

The meetups are filtered by date as they are loaded into MeetupCollection. If the meetup time is before the current time then it will not be added to MeetupCollection

2019-04-20 20:51 UTC, windust requested changes

2019-04-20 20:51 UTC, windust commented on src/main/java/com/spinningnoodle/communitymanager/controller/AdminController.java
> +        Authentication auth = SecurityContextHolder.getContext().getAuthentication();
use this instead of parsing the JSON (https://stackoverflow.com/questions/46547833/spring-security-how-to-get-details-from-the-principal) 

you want to make it so that the parsing is not error-prone (like dependent on how is structured... json can have many enders, so is best to be explicit on it like the above.

2019-04-20 20:51 UTC, windust commented on src/main/java/com/spinningnoodle/communitymanager/controller/AdminController.java
> +    //Route cannot equal "logout" because that is oauth default
can we use oauth logout then?
or redirect to that after finishing here?

2019-04-22 02:25 UTC, Troemer16 commented on src/main/java/com/spinningnoodle/communitymanager/controller/AdminController.java
> +    //Route cannot equal "logout" because that is oauth default
Cannot use oauth logout because we also need to logout on out side

I could redirect there but currently using SecurityContextLogoutHandler to do the same thing. Would you rather there be a redirect here to the google logout?

2019-04-22 02:25 UTC, Troemer16 commented on src/main/java/com/spinningnoodle/communitymanager/controller/AdminController.java
> +        Authentication auth = SecurityContextHolder.getContext().getAuthentication();
Fixed

2019-04-22 02:55 UTC, merged